version: '3'

services:

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.opendistro
      args:
        - OPENDISTRO_VERSION=${OPENDISTRO_VERSION:-latest}
    environment:
      - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    user: elasticsearch